#!/bin/bash

echo "=== Available MIS Algorithm Configurations ==="
echo ""
echo "Fast MIS Algorithm (Randomized):"
echo "  FastMIS-Complete      - Complete graph with 6 nodes"
echo "  FastMIS-Complete-Large - Complete graph with 10 nodes"
echo "  FastMIS-Grid-Small    - 3x3 grid topology"
echo "  FastMIS-Grid-Medium   - 4x4 grid topology"
echo "  FastMIS-Fast          - Fast execution with shorter timeouts"
echo ""
echo "Slow MIS Algorithm (Deterministic - Algorithm 7.3):"
echo "  SlowMIS-Complete      - Complete graph with 6 nodes"
echo "  SlowMIS-Complete-Large - Complete graph with 10 nodes"
echo "  SlowMIS-Grid-Small    - 3x3 grid topology"
echo "  SlowMIS-Grid-Medium   - 4x4 grid topology"
echo "  SlowMIS-Fast          - Fast execution with shorter check interval"
echo ""
echo "Ring Algorithm (original):"
echo "  SimpleRing            - Ring with 4 nodes"
echo "  MediumRing            - Ring with 6 nodes" 
echo "  LargeRing             - Ring with 8 nodes"
echo ""
echo "Key Differences:"
echo "  • Fast MIS: Uses random values, non-deterministic results"
echo "  • Slow MIS: Uses node IDs only, deterministic results"
echo "  • Both use proper message passing for neighbor discovery"
echo ""
echo "Usage examples:"
echo "  ./demo -c FastMIS-Grid-Small -u Cmdenv --sim-time-limit=10s"
echo "  ./demo -c SlowMIS-Complete -u Cmdenv --sim-time-limit=10s"
echo "  ./demo -c SimpleRing -u Cmdenv --sim-time-limit=10s"
echo ""
echo "To run with GUI: ./demo -c <config> -u Qtenv"
echo "To run with command line: ./demo -c <config> -u Cmdenv"